### ISSUE TITLE
Crash/slowdown when asynchronously stepping to point in large files

### ISSUE THREAD

**Issue by MevenBertrand** [coq-community/vscoq-legacy#54]
When stepping through large files (those of [MetaCoq](https://github.com/MetaCoq/metacoq)) using the asynchronous interpret to point feature, I often get first a slowdown/freeze of my system, then recover from the slowdown but with a greyed out proof goal window. 
Using the *synchronous* interpret to point seems to work, and stepping manually in smaller steps also mitigates the issue.

I guess this means that something, somewhere, chokes on my file then crashes, but not sure what, nor how I can debug this further – I don’t know much about VsCode.

**Comment by Blaisorblade** [comment]
Unfortunately there are no plans to fix STM problems here... So closing
